version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dnd
      POSTGRES_PASSWORD: dndpass
      POSTGRES_DB: dnddb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init-extensions.sql:/docker-entrypoint-initdb.d/10-extensions.sql
      # Conditionally load sample data based on environment variables
      - ${CHARACTER_DATA_FILE:-./db/empty-character-data.sql}:/docker-entrypoint-initdb.d/30-character-data.sql
      - ${ITEM_DATA_FILE:-./db/empty-item-data.sql}:/docker-entrypoint-initdb.d/40-item-data.sql

  backend:
    build: ./backend/dndapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dnddb
      SPRING_DATASOURCE_USERNAME: dnd
      SPRING_DATASOURCE_PASSWORD: dndpass
    expose:
      - "8080"
    depends_on:
      - db

  frontend:
    build: ./frontend/dnd-app
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data: