-- D&D Classes, Races, Backgrounds, and Subclasses for PostgreSQL
-- Generated by OpenAI GPT-3.5-Turbo
-- For fresh database instances


-- ===============================================
-- MANUALLY ENTERED
-- ===============================================

-- Wizard Class
INSERT INTO class (
    class_uuid, name, description, hit_dice_value
) VALUES (
    gen_random_uuid(), 'Wizard', 'A scholarly magic-user capable of manipulating the structures of spellcasting to cast spells of lower level a greater number of times per day and cast spells of greater power. Wizards are arcane spellcasters who depend on intensive study to create their magic. They examine musty tomes of arcane lore, debate magical theory, and practice minor magics until they master their craft. For a wizard, magic is not a talent but a difficult, rewarding art.', 'D6'
);

-- Paladin Class  
INSERT INTO class (
    class_uuid, name, description, hit_dice_value
) VALUES (
    gen_random_uuid(), 'Paladin', 'A holy warrior bound to a sacred oath. Whether sworn before a god''s altar and the witness of a priest, in a sacred glade before nature spirits and fey beings, or in a moment of desperation and grief with the dead as the only witness, a paladin''s oath is a powerful bond. It is a source of power that turns a devout warrior into a blessed champion.', 'D10'
);

-- ===============================================
-- CLASSES
-- ===============================================

INSERT INTO class (
    class_uuid, name, description, hit_dice_value
) VALUES (
    gen_random_uuid() ,'Barbarian', 'Choose two from Animal Handling, Athletics, Intimidation, Nature, Perception, and Survival', 'D12'
);
INSERT INTO class (
    class_uuid, name, description, hit_dice_value
) VALUES (
    gen_random_uuid() ,'Bard', 'Bards are performers and storytellers, using their artistic talents to captivate audiences and manipulate emotions. They are versatile spellcasters, capable of weaving magic through music and inspiring their allies in battle.', 'D8'
);
INSERT INTO class (
    class_uuid, name, description, hit_dice_value
) VALUES (
    gen_random_uuid() ,'Cleric', 'Cleric class in Dungeons & Dragons. The cleric is a versatile class, capable of filling various roles in a party. They have access to divine magic and can serve as healers, buffers, or damage dealers.', 'D8'
);
INSERT INTO class (
    class_uuid, name, description, hit_dice_value
) VALUES (
    gen_random_uuid() ,'Druid', 'Druid class in Dungeons & Dragons. The Druid is a spellcaster with a deep connection to nature and the ability to shape-shift into various forms.', 'D8'
);
INSERT INTO class (
    class_uuid, name, description, hit_dice_value
) VALUES (
    gen_random_uuid() ,'Fighter', 'Choose two skills from Acrobatics, Animal Handling, Athletics, History, Insight, Intimidation, Perception, and Survival', 'D10'
);
INSERT INTO class (
    class_uuid, name, description, hit_dice_value
) VALUES (
    gen_random_uuid() ,'Monk', 'Monk class in Dungeons & Dragons. Proficient in Acrobatics, Athletics, History, Insight, Religion, Stealth. Can choose artisan''s tools or musical instrument. Proficient in Simple Weapons, Shortswords, DEX and STR saving throws. Starting equipment includes Darts. Can choose between a shortsword or any simple weapon, and between a dungeoneer''s pack or an explorer''s pack. Prerequisites for multiclassing: DEX and WIS scores of at least 13. Subclass: Open Hand.', 'D8'
);

INSERT INTO class (
    class_uuid, name, description, hit_dice_value
) VALUES (
    gen_random_uuid() ,'Ranger', 'Choose three from Animal Handling, Athletics, Insight, Investigation, Nature, Perception, Stealth, and Survival', 'D10'
);
INSERT INTO class (
    class_uuid, name, description, hit_dice_value
) VALUES (
    gen_random_uuid() ,'Rogue', 'Choose four from Acrobatics, Athletics, Deception, Insight, Intimidation, Investigation, Perception, Performance, Persuasion, Sleight of Hand, and Stealth', 'D8'
);
INSERT INTO class (
    class_uuid, name, description, hit_dice_value
) VALUES (
    gen_random_uuid() ,'Sorcerer', 'Choose two from Arcana, Deception, Insight, Intimidation, Persuasion, and Religion', 'D6'
);
INSERT INTO class (
    class_uuid, name, description, hit_dice_value
) VALUES (
    gen_random_uuid() ,'Warlock', 'Warlock class in Dungeons & Dragons. The Warlock is a spellcaster that draws power from a pact made with a powerful being, gaining magical abilities and eldritch invocations.', 'D8'
);

-- ===============================================
-- RACES
-- ===============================================

INSERT INTO race (
    race_uuid, name, stat_increases
) VALUES (
    gen_random_uuid(), 'Dragonborn', '{"strength": 2, "dexterity": 0, "constitution": 0, "intelligence": 0, "wisdom": 0, "charisma": 1}'
);
INSERT INTO race (
    race_uuid, name, stat_increases
) VALUES (
    gen_random_uuid(), 'Dwarf', '{"strength": 0, "dexterity": 0, "constitution": 2, "intelligence": 0, "wisdom": 0, "charisma": 0}'
);
INSERT INTO race (
    race_uuid, name, stat_increases
) VALUES (
    gen_random_uuid(), 'Elf', '{"strength": 0, "dexterity": 2, "constitution": 0, "intelligence": 0, "wisdom": 0, "charisma": 0}'
);
INSERT INTO race (
    race_uuid, name, stat_increases
) VALUES (
    gen_random_uuid(), 'Gnome', '{"strength": 0, "dexterity": 0, "constitution": 0, "intelligence": 2, "wisdom": 0, "charisma": 0}'
);
INSERT INTO race (
    race_uuid, name, stat_increases
) VALUES (
    gen_random_uuid(), 'Half-Elf', '{"strength": 1, "dexterity": 1, "constitution": 1, "intelligence": 1, "wisdom": 1, "charisma": 2}'
);
INSERT INTO race (
    race_uuid, name, stat_increases
) VALUES (
    gen_random_uuid(), 'Half-Orc', '{"strength": 2, "dexterity": 0, "constitution": 1, "intelligence": 0, "wisdom": 0, "charisma": 0}'
);
INSERT INTO race (
    race_uuid, name, stat_increases
) VALUES (
    gen_random_uuid(), 'Halfling', '{"strength": 0, "dexterity": 2, "constitution": 0, "intelligence": 0, "wisdom": 0, "charisma": 0}'
);
INSERT INTO race (
    race_uuid, name, stat_increases
) VALUES (
    gen_random_uuid(), 'Human', '{"strength": 1, "dexterity": 1, "constitution": 1, "intelligence": 1, "wisdom": 1, "charisma": 1}'
);
INSERT INTO race (
    race_uuid, name, stat_increases
) VALUES (
    gen_random_uuid(), 'Tiefling', '{"strength": 0, "dexterity": 0, "constitution": 0, "intelligence": 1, "wisdom": 0, "charisma": 2}'
);

-- ===============================================
-- BACKGROUNDS
-- ===============================================

INSERT INTO background (
    background_uuid, name, description, starting_gold
) VALUES (
    gen_random_uuid() ,'Acolyte', 'Command respect of those who share your faith, perform religious ceremonies, receive free healing at temples, have ties to a specific temple, and can call upon priests for assistance.', 25
);

-- ===============================================
-- SUBCLASSES
-- ===============================================

INSERT INTO subclass (subclass_uuid, name, class_source) 
SELECT gen_random_uuid(), 'Berserker', class_uuid FROM class WHERE name = 'Barbarian';
INSERT INTO subclass (subclass_uuid, name, class_source) 
SELECT gen_random_uuid(), 'Champion', class_uuid FROM class WHERE name = 'Fighter';
INSERT INTO subclass (subclass_uuid, name, class_source) 
SELECT gen_random_uuid(), 'Devotion', class_uuid FROM class WHERE name = 'Paladin';
INSERT INTO subclass (subclass_uuid, name, class_source) 
SELECT gen_random_uuid(), 'Draconic', class_uuid FROM class WHERE name = 'Sorcerer';
INSERT INTO subclass (subclass_uuid, name, class_source) 
SELECT gen_random_uuid(), 'Evocation', class_uuid FROM class WHERE name = 'Wizard';
INSERT INTO subclass (subclass_uuid, name, class_source) 
SELECT gen_random_uuid(), 'Fiend', class_uuid FROM class WHERE name = 'Warlock';
INSERT INTO subclass (subclass_uuid, name, class_source) 
SELECT gen_random_uuid(), 'Hunter', class_uuid FROM class WHERE name = 'Ranger';
INSERT INTO subclass (subclass_uuid, name, class_source) 
SELECT gen_random_uuid(), 'Land', class_uuid FROM class WHERE name = 'Druid';
INSERT INTO subclass (subclass_uuid, name, class_source) 
SELECT gen_random_uuid(), 'Life', class_uuid FROM class WHERE name = 'Cleric';
INSERT INTO subclass (subclass_uuid, name, class_source) 
SELECT gen_random_uuid(), 'Lore', class_uuid FROM class WHERE name = 'Bard';
INSERT INTO subclass (subclass_uuid, name, class_source) 
SELECT gen_random_uuid(), 'Open Hand', class_uuid FROM class WHERE name = 'Monk';
INSERT INTO subclass (subclass_uuid, name, class_source) 
SELECT gen_random_uuid(), 'Thief', class_uuid FROM class WHERE name = 'Rogue';
