-- D&D Classes, Races, Backgrounds, and Subclasses for PostgreSQL
-- Generated by OpenAI GPT-3.5-Turbo
-- For fresh database instances


-- ===============================================
-- START: MANUALLY ENTERED
-- ===============================================

-- Wizard Class
INSERT INTO class (
    name, description, hit_dice_value
) VALUES (
    'Wizard', 'A scholarly magic-user capable of manipulating the structures of spellcasting to cast spells of lower level a greater number of times per day and cast spells of greater power. Wizards are arcane spellcasters who depend on intensive study to create their magic. They examine musty tomes of arcane lore, debate magical theory, and practice minor magics until they master their craft. For a wizard, magic is not a talent but a difficult, rewarding art.', 'D6'
);

-- Paladin Class  
INSERT INTO class (
    name, description, hit_dice_value
) VALUES (
    'Paladin', 'A holy warrior bound to a sacred oath. Whether sworn before a god''s altar and the witness of a priest, in a sacred glade before nature spirits and fey beings, or in a moment of desperation and grief with the dead as the only witness, a paladin''s oath is a powerful bond. It is a source of power that turns a devout warrior into a blessed champion.', 'D10'
);


-- ===============================================
-- CLASSES
-- ===============================================

INSERT INTO class (
    name, description, hit_dice_value
) VALUES (
    'Barbarian', 'Barbarian class in D&D is a fierce warrior of primitive background who can enter a battle rage.', 'D12'
);
INSERT INTO class (
    name, description, hit_dice_value
) VALUES (
    'Bard', 'Bards are performers and storytellers, using their artistic talents to captivate audiences and manipulate emotions. They can cast spells through the power of music and are skilled in a variety of skills and musical instruments.', 'D8'
);
INSERT INTO class (
    name, description, hit_dice_value
) VALUES (
    'Cleric', 'Cleric class in Dungeons & Dragons. The cleric is a versatile class that can serve as a healer, support, or frontline combatant. They draw their power from their devotion to a deity and are proficient in divine magic.', 'D8'
);
INSERT INTO class (
    name, description, hit_dice_value
) VALUES (
    'Druid', 'Druid class in Dungeons & Dragons. The Druid is a spellcaster with a deep connection to nature, able to shape-shift and cast nature-based spells.', 'D8'
);
INSERT INTO class (
    name, description, hit_dice_value
) VALUES (
    'Fighter', 'Choose two skills from Acrobatics, Animal Handling, Athletics, History, Insight, Intimidation, Perception, and Survival', 'D10'
);
INSERT INTO class (
    name, description, hit_dice_value
) VALUES (
    'Monk', 'Monk class in Dungeons & Dragons. Proficient in Acrobatics, Athletics, History, Insight, Religion, Stealth. Can choose artisan''s tools or musical instrument. Proficient in Simple Weapons, Shortswords, DEX and STR saving throws. Starting equipment includes Darts. Starting equipment options include shortsword or simple weapon, dungeoneer''s pack or explorer''s pack. Can multiclass with DEX and WIS prerequisites. Subclass: Open Hand.', 'D8'
);

INSERT INTO class (
    name, description, hit_dice_value
) VALUES (
    'Ranger', 'Choose three from Animal Handling, Athletics, Insight, Investigation, Nature, Perception, Stealth, and Survival', 'D10'
);
INSERT INTO class (
    name, description, hit_dice_value
) VALUES (
    'Rogue', 'Choose four from Acrobatics, Athletics, Deception, Insight, Intimidation, Investigation, Perception, Performance, Persuasion, Sleight of Hand, and Stealth', 'D8'
);
INSERT INTO class (
    name, description, hit_dice_value
) VALUES (
    'Sorcerer', 'Sorcerer class in Dungeons & Dragons. Masters of innate magic, sorcerers cast spells through sheer force of personality.', 'D6'
);
INSERT INTO class (
    name, description, hit_dice_value
) VALUES (
    'Warlock', 'Choose two skills from Arcana, Deception, History, Intimidation, Investigation, Nature, and Religion. Light Armor, Simple Weapons, Saving Throw: WIS, Saving Throw: CHA. WIS, CHA. Starting equipment: Dagger x2, Leather Armor x1. (a) a light crossbow and 20 bolts or (b) any simple weapon. (a) a component pouch or (b) an arcane focus. (a) a scholar’s pack or (b) a dungeoneer’s pack. Any simple weapon. Prerequisites: CHA 13. Light Armor, Simple Weapons. Fiend. Cantrips, Spell Slots, Spells Known of 1st Level and Higher, Spellcasting Ability, Spellcasting Focus.', 'D8'
);

-- ===============================================
-- RACES
-- ===============================================

INSERT INTO race (
    name, stat_increases
) VALUES (
    'Dragonborn', '{"strength": 2, "dexterity": 0, "constitution": 0, "intelligence": 0, "wisdom": 0, "charisma": 1}'
);
INSERT INTO race (
    name, stat_increases
) VALUES (
    'Dwarf', '{"strength": 0, "dexterity": 0, "constitution": 2, "intelligence": 0, "wisdom": 0, "charisma": 0}'
);
INSERT INTO race (
    name, stat_increases
) VALUES (
    'Elf', '{"strength": 0, "dexterity": 2, "constitution": 0, "intelligence": 0, "wisdom": 0, "charisma": 0}'
);
INSERT INTO race (
    name, stat_increases
) VALUES (
    'Gnome', '{"strength": 0, "dexterity": 0, "constitution": 0, "intelligence": 2, "wisdom": 0, "charisma": 0}'
);
INSERT INTO race (
    name, stat_increases
) VALUES (
    'Half-Elf', '{"strength": 1, "dexterity": 1, "constitution": 1, "intelligence": 1, "wisdom": 1, "charisma": 2}'
);
INSERT INTO race (
    name, stat_increases
) VALUES (
    'Half-Orc', '{"strength": 2, "dexterity": 0, "constitution": 1, "intelligence": 0, "wisdom": 0, "charisma": 0}'
);
INSERT INTO race (
    name, stat_increases
) VALUES (
    'Halfling', '{"strength": 0, "dexterity": 2, "constitution": 0, "intelligence": 0, "wisdom": 0, "charisma": 0}'
);
INSERT INTO race (
    name, stat_increases
) VALUES (
    'Human', '{"strength": 1, "dexterity": 1, "constitution": 1, "intelligence": 1, "wisdom": 1, "charisma": 1}'
);
INSERT INTO race (
    name, stat_increases
) VALUES (
    'Tiefling', '{"strength": 0, "dexterity": 0, "constitution": 0, "intelligence": 1, "wisdom": 0, "charisma": 2}'
);

-- ===============================================
-- BACKGROUNDS
-- ===============================================

INSERT INTO background (
    name, description, starting_gold
) VALUES (
    'Acolyte', 'Command respect of those who share your faith, perform religious ceremonies, receive free healing at temples, and have ties to a specific temple.', 25
);

-- ===============================================
-- SUBCLASSES
-- ===============================================

INSERT INTO subclass (name, class_source) 
SELECT 'Berserker', class_uuid FROM class WHERE name = 'Barbarian';
INSERT INTO subclass (name, class_source) 
SELECT 'Champion', class_uuid FROM class WHERE name = 'Fighter';
INSERT INTO subclass (name, class_source) 
SELECT 'Devotion', class_uuid FROM class WHERE name = 'Paladin';
INSERT INTO subclass (name, class_source) 
SELECT 'Draconic', class_uuid FROM class WHERE name = 'Sorcerer';
INSERT INTO subclass (name, class_source) 
SELECT 'Evocation', class_uuid FROM class WHERE name = 'Wizard';
INSERT INTO subclass (name, class_source) 
SELECT 'Fiend', class_uuid FROM class WHERE name = 'Warlock';
INSERT INTO subclass (name, class_source) 
SELECT 'Hunter', class_uuid FROM class WHERE name = 'Ranger';
INSERT INTO subclass (name, class_source) 
SELECT 'Land', class_uuid FROM class WHERE name = 'Druid';
INSERT INTO subclass (name, class_source) 
SELECT 'Life', class_uuid FROM class WHERE name = 'Cleric';
INSERT INTO subclass (name, class_source) 
SELECT 'Lore', class_uuid FROM class WHERE name = 'Bard';
INSERT INTO subclass (name, class_source) 
SELECT 'Open Hand', class_uuid FROM class WHERE name = 'Monk';
INSERT INTO subclass (name, class_source) 
SELECT 'Thief', class_uuid FROM class WHERE name = 'Rogue';
